### ISSUE TITLE
Doesn't update header.tpl

### ISSUE THREAD

**Issue by d2boy** [dean992008/gulp-opencart-refresh#1]
Refreshes page, but doesn't update the cache.

**Comment by dean992008** [comment]
The module after the trigger automatically presses the cache clear button in the Admin panel. I recommend to check the operation of this button. Also write what is your version of opencart.

**Comment by d2boy** [comment]
I found out the problem - one of the ocmod extensions was modifying header.tpl
This prevents cache cleaning of the header.tpl
